const $=id=>document.getElementById(id);let tf='15min';
const chart=LightweightCharts.createChart($('chart'),{layout:{background:{color:'#0d141e'},textColor:'#8794a6'},grid:{vertLines:{color:'#17212d'},horzLines:{color:'#17212d'}},rightPriceScale:{borderColor:'#263342'},timeScale:{timeVisible:true,borderColor:'#263342'}});
const candles=chart.addCandlestickSeries({upColor:'#39d995',downColor:'#ff6d7e',borderUpColor:'#39d995',borderDownColor:'#ff6d7e',wickUpColor:'#39d995',wickDownColor:'#ff6d7e'});
const high=chart.addLineSeries({color:'#e3b65d',lineStyle:2,lineWidth:1,priceLineVisible:false,lastValueVisible:false});const low=chart.addLineSeries({color:'#70a9ff',lineStyle:2,lineWidth:1,priceLineVisible:false,lastValueVisible:false});
const entryLine=chart.addLineSeries({color:'#39d995',lineWidth:1,priceLineVisible:false});const slLine=chart.addLineSeries({color:'#ff6d7e',lineWidth:1,priceLineVisible:false});const tp2Line=chart.addLineSeries({color:'#e3b65d',lineWidth:1,priceLineVisible:false});
const fmt=x=>Number.isFinite(Number(x))?Number(x).toFixed(2):'—';const time=x=>x?new Date(Number(x)*1000).toLocaleString([],{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function flat(s,data,v){s.setData(Number.isFinite(Number(v))&&data.length?[{time:data[0].time,value:Number(v)},{time:data.at(-1).time,value:Number(v)}]:[])}
async function load(){ $('status').textContent='LOADING';try{const r=await fetch('/api/data?interval='+tf+'&outputsize=300',{cache:'no-store'}),d=await r.json();if(!d.success)throw Error(d.error);const data=d.candles.map(x=>({time:+x.time,open:+x.open,high:+x.high,low:+x.low,close:+x.close}));candles.setData(data);high.setData((d.swings.highs||[]).map(x=>({time:+x.time,value:+x.price})));low.setData((d.swings.lows||[]).map(x=>({time:+x.time,value:+x.price})));const marks=(d.liquidity.sweeps||[]).map(x=>({time:+x.time,position:x.type==='BULLISH'?'belowBar':'aboveBar',shape:x.type==='BULLISH'?'arrowUp':'arrowDown',color:x.type==='BULLISH'?'#39d995':'#ff6d7e',text:x.type==='BULLISH'?'SWEEP ↑':'SWEEP ↓'}));candles.setMarkers(marks.sort((a,b)=>a.time-b.time));
const s=d.signal||{};$('signal').textContent=s.direction||'WAIT';$('signal').className=s.direction==='BUY'?'buy':s.direction==='SELL'?'sell':'wait';$('signalMeta').textContent=s.time?'Confirmed '+time(s.time):s.rejection||'No active confirmed signal';$('prob').textContent=(s.probability||0)+'%';$('score').textContent=s.score||0;$('price').textContent=fmt(d.market.price);$('atr').textContent=fmt(d.diagnostics?.atr);
const p=d.tradePlan;$('planState').textContent=p?(p.direction+' ACTIVE'):'No active trade';['entry','sl','tp1','tp2','tp3','risk'].forEach(k=>$(k).textContent=p?fmt(p[k==='sl'?'stopLoss':k]):'—');flat(entryLine,data,p?.entry);flat(slLine,data,p?.stopLoss);flat(tp2Line,data,p?.tp2);
const h=d.history||{},z=h.summary||{};$('summary').innerHTML='<span>Trades <b>'+z.totalTrades+'</b></span><span class="win">Win <b>'+z.wins+'</b></span><span class="loss">Loss <b>'+z.losses+'</b></span><span>Win Rate <b>'+z.winRate+'%</b></span><span>Total R <b>'+fmt(z.totalR)+'R</b></span><span class="open">Open <b>'+z.open+'</b></span>';
$('history').innerHTML=(h.trades||[]).slice().reverse().slice(0,50).map(t=>'<tr><td>'+time(t.signalTime)+'</td><td class="'+(t.direction==='BUY'?'buy':'sell')+'">'+t.direction+'</td><td>'+fmt(t.entry)+'</td><td>'+fmt(t.stopLoss)+'</td><td>'+fmt(t.tp1)+'</td><td>'+fmt(t.tp2)+'</td><td class="'+(t.result==='WIN'?'win':t.result==='LOSS'?'loss':'open')+'">'+t.result+'</td><td>'+((+t.realizedR>0)?'+':'')+fmt(t.realizedR)+'R</td></tr>').join('')||'<tr><td colspan="8">No confirmed trades.</td></tr>';
const q=d.diagnostics||{};$('diagnostics').innerHTML='<div><span>Latest price</span><b>'+fmt(q.latestPrice)+'</b></div><div><span>Latest swing high</span><b>'+fmt(q.latestSwingHigh)+'</b></div><div><span>Latest swing low</span><b>'+fmt(q.latestSwingLow)+'</b></div><div><span>Latest sweep</span><b>'+q.latestSweep+'</b></div><div><span>Confirmation</span><b>'+q.confirmation+'</b></div><div><span>Volume confirmed</span><b>'+q.volumeConfirmed+'</b></div><div><span>Risk filter</span><b>'+((q.riskFilter||{}).passed?'PASSED':'WAIT')+'</b></div>';
$('status').textContent='LIVE · '+time(d.market.lastCandleTime);chart.timeScale().fitContent()}catch(e){$('status').textContent='ERROR';$('signalMeta').textContent=e.message}}
document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{tf=b.dataset.tf;document.querySelectorAll('[data-tf]').forEach(x=>x.classList.remove('active'));b.classList.add('active');load()});$('refresh').onclick=load;addEventListener('resize',()=>chart.applyOptions({width:$('chart').clientWidth}));load();setInterval(load,60000);
