let symbol='BTCUSDT',interval='15m',loading=false,ws=null;
const $=id=>document.getElementById(id);
const fmt=x=>Number.isFinite(Number(x))?Number(x).toFixed(Number(x)>100?2:6):'—';
const tm=x=>x?new Date(Number(x)*1000).toLocaleString([], {month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const chart=LightweightCharts.createChart($('chart'),{width:$('chart').clientWidth,height:$('chart').clientHeight,layout:{background:{color:'#06101a'},textColor:'#8799aa'},grid:{vertLines:{color:'#102233'},horzLines:{color:'#102233'}},rightPriceScale:{borderColor:'#1b3448'},timeScale:{timeVisible:true,secondsVisible:false,borderColor:'#1b3448'}});
const series=chart.addCandlestickSeries({upColor:'#35dfa0',downColor:'#ff6578',borderUpColor:'#35dfa0',borderDownColor:'#ff6578',wickUpColor:'#35dfa0',wickDownColor:'#ff6578'});
const entryLine=chart.addLineSeries({color:'#35dfa0',lineWidth:1,priceLineVisible:false,lastValueVisible:true,title:'ENTRY'});
const slLine=chart.addLineSeries({color:'#ff6578',lineWidth:1,priceLineVisible:false,lastValueVisible:true,title:'SL'});
const tp2Line=chart.addLineSeries({color:'#e4bb5d',lineWidth:1,priceLineVisible:false,lastValueVisible:true,title:'TP2'});
let lastCandles=[];
function setStatus(x,live){$('status').textContent=x;$('status').className='status '+(live?'live':'')}
function setLines(p){const d=lastCandles,line=(s,v)=>{if(!Number.isFinite(Number(v))||d.length<2)s.setData([]);else s.setData([{time:d[0].time,value:Number(v)},{time:d[d.length-1].time,value:Number(v)}])};line(entryLine,p&&p.entry);line(slLine,p&&p.stopLoss);line(tp2Line,p&&p.tp2)}
function render(d){lastCandles=d.candles||[];series.setData(lastCandles.map(c=>({time:c.time,open:c.open,high:c.high,low:c.low,close:c.close})));chart.timeScale().fitContent();const s=d.signal||{},p=d.tradePlan;
$('signal').textContent=s.direction&&s.direction!=='WAIT'?s.direction:'WAIT';$('signal').className=s.direction==='BUY'?'buy':s.direction==='SELL'?'sell':'';$('signalMeta').textContent=s.direction&&s.direction!=='WAIT'?'Confirmed setup · next candle OPEN entry':(s.rejection||'No confirmed setup');
$('price').textContent=fmt(d.market.price);$('prob').textContent=s.probability?String(s.probability)+'%':'—';$('score').textContent=s.score??'—';$('candles').textContent=d.market.closedCandleCount||'—';$('atr').textContent=fmt(d.diagnostics&&d.diagnostics.atr);$('signalLabel').textContent=interval.toUpperCase()+' CURRENT SIGNAL';$('chartTitle').textContent=d.market.symbol.replace('USDT','/USDT')+' · '+interval.toUpperCase();
if(p){$('planState').textContent='Confirmed trade';$('entry').textContent=fmt(p.entry);$('sl').textContent=fmt(p.stopLoss);$('tp1').textContent=fmt(p.tp1);$('tp2').textContent=fmt(p.tp2);$('tp3').textContent=fmt(p.tp3);$('tp4').textContent=fmt(p.tp4);setLines(p)}else{$('planState').textContent='No confirmed trade';['entry','sl','tp1','tp2','tp3','tp4'].forEach(id=>$(id).textContent='—');setLines(null)}
const h=d.history||{},z=h.summary||{};$('summary').innerHTML=[['Trades',z.totalTrades||0,''],['Win',z.wins||0,'win'],['Loss',z.losses||0,'loss'],['Win Rate',String(z.winRate||0)+'%',''],['Total R',Number(z.totalR||0).toFixed(2)+'R','']].map(x=>'<span class="'+x[2]+'">'+x[0]+' <b>'+x[1]+'</b></span>').join('');
$('history').innerHTML=(h.trades||[]).slice(0,60).map(x=>'<tr><td>'+tm(x.signalTime)+'</td><td class="'+(x.direction==='BUY'?'buy':'sell')+'">'+x.direction+'</td><td>'+fmt(x.entry)+'</td><td>'+fmt(x.stopLoss)+'</td><td>'+fmt(x.tp1)+'</td><td>'+fmt(x.tp2)+'</td><td>'+fmt(x.tp3)+'</td><td>'+fmt(x.tp4)+'</td><td>'+((x.hitTPs||[]).join(', ')||'—')+'</td><td class="'+(x.result==='WIN'?'win':x.result==='LOSS'?'loss':'open')+'">'+x.result+'</td><td>'+((Number(x.realizedR||0)>0?'+':'')+Number(x.realizedR||0).toFixed(2))+'R</td></tr>').join('')||'<tr><td colspan="11">No historical confirmed trades.</td></tr>';
const q=d.diagnostics||{};$('diag').innerHTML=[['Latest price',fmt(q.latestPrice)],['Swing high',fmt(q.latestSwingHigh)],['Swing low',fmt(q.latestSwingLow)],['Latest sweep',q.latestSweep||'NONE'],['Confirmation',q.confirmation||'NONE'],['Volume confirmed',q.volumeConfirmed?'YES':'NO'],['Risk filter',q.riskFilter&&q.riskFilter.rejected?'REJECTED · '+q.riskFilter.reason:q.riskFilter&&q.riskFilter.passed?'PASSED':'WAIT']].map(x=>'<div><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')}
async function load(){if(loading)return;loading=true;setStatus('LOADING');try{const r=await fetch('/api/crypto/data?symbol='+symbol+'&interval='+interval+'&outputsize=300',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Crypto API error');render(d);setStatus('LIVE',true)}catch(e){setStatus('ERROR');$('signalMeta').textContent=e.message||'Crypto data unavailable'}finally{loading=false}}
function connect(){if(ws)try{ws.close()}catch(_){}const stream=symbol.toLowerCase()+'@kline_'+interval;ws=new WebSocket('wss://stream.binance.com:443/ws/'+stream);ws.onopen=()=>setStatus('LIVE',true);ws.onmessage=e=>{try{const d=JSON.parse(e.data),k=d.k;if(!k)return;const c={time:Math.floor(k.t/1000),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c)};const i=lastCandles.findIndex(x=>x.time===c.time);if(i>=0)lastCandles[i]={...lastCandles[i],...c};else{lastCandles.push(c);lastCandles=lastCandles.slice(-300)}series.setData(lastCandles.map(x=>({time:x.time,open:x.open,high:x.high,low:x.low,close:x.close})));$('price').textContent=fmt(c.close);if(k.x)load()}catch(_){}};ws.onclose=()=>setTimeout(()=>{if(document.visibilityState!=='hidden')connect()},3000)}
document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{symbol=b.dataset.symbol;document.querySelectorAll('[data-symbol]').forEach(x=>x.classList.toggle('active',x===b));load();connect()});
document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{interval=b.dataset.tf;document.querySelectorAll('[data-tf]').forEach(x=>x.classList.toggle('active',x===b));load();connect()});
$('refresh').onclick=load;window.addEventListener('resize',()=>chart.applyOptions({width:$('chart').clientWidth,height:$('chart').clientHeight}));load();connect();setInterval(load,30000);