import { CONFIG, analyze, buildHistory } from '../../src/strategy.js';

const SYMBOLS = new Set(['BTCUSDT','ETHUSDT','SOLUSDT','BNBUSDT','XRPUSDT','DOGEUSDT']);
const INTERVALS = new Set(['5m','15m']);
const STEP = {'5m':300,'15m':900};
const BINANCE='https://api.binance.com/api/v3/klines';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'})}}
function normalize(rows){return rows.map(r=>({time:Math.floor(Number(r[0])/1000),open:Number(r[1]),high:Number(r[2]),low:Number(r[3]),close:Number(r[4]),volume:Number(r[5]||0)})).filter(c=>[c.time,c.open,c.high,c.low,c.close].every(Number.isFinite))}
async function fetchBinance(symbol,interval,limit){const u=new URL(BINANCE);u.searchParams.set('symbol',symbol);u.searchParams.set('interval',interval);u.searchParams.set('limit',String(Math.min(500,Math.max(100,limit))));const r=await fetch(u.toString(),{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!Array.isArray(d))throw Error(d?.msg||'Binance market data unavailable');const c=normalize(d);if(c.length<50)throw Error('Binance returned insufficient candles');return c}
function activePlan(a){if(!a.signal||a.signal.direction==='WAIT'||!a.tradePlan)return null;return{direction:a.signal.direction,probability:a.signal.probability,score:a.signal.score,entry:a.tradePlan.entry,stopLoss:a.tradePlan.stopLoss,tp1:a.tradePlan.tp1,tp2:a.tradePlan.tp2,tp3:a.tradePlan.tp3,tp4:a.tradePlan.tp4,risk:a.tradePlan.risk,signalTime:a.signal.entryTime||a.signal.time,confirmationTime:a.signal.confirmation?.time||null,entryRule:'NEXT_CANDLE_OPEN'}}
export async function onRequest(context){const{request}=context;if(request.method!=='GET')return json({success:false,error:'Method not allowed'},405);try{const u=new URL(request.url),symbol=String(u.searchParams.get('symbol')||'BTCUSDT').toUpperCase(),interval=INTERVALS.has(u.searchParams.get('interval'))?u.searchParams.get('interval'):'15m';if(!SYMBOLS.has(symbol))return json({success:false,error:'Unsupported crypto symbol'},400);const n=Number(u.searchParams.get('outputsize')||CONFIG.outputSize),outputsize=Number.isFinite(n)?Math.min(500,Math.max(100,Math.floor(n))):300,candles=await fetchBinance(symbol,interval,outputsize),step=STEP[interval],now=Math.floor(Date.now()/1000),closed=candles.filter(c=>c.time+step<=now),analysisCandles=closed.length?closed:candles.slice(0,-1),entryCandle=candles.find(c=>c.time>analysisCandles.at(-1).time)||null;if(analysisCandles.length<50)throw Error('Not enough completed candles');const analysis=analyze(analysisCandles,null,entryCandle,{requireStructureAlignment:false}),history=buildHistory(analysisCandles,analysis.swings,symbol),active=activePlan(analysis),wins=history.filter(t=>t.result==='WIN').length,losses=history.filter(t=>t.result==='LOSS').length,totalR=history.reduce((s,t)=>s+Number(t.realizedR||0),0);return json({success:true,market:{symbol,interval,price:candles.at(-1).close,lastCandleTime:candles.at(-1).time,candleCount:candles.length,closedCandleCount:analysisCandles.length},dataProvider:{name:'Binance Spot Market Data',endpoint:'api.binance.com/api/v3/klines'},strategy:{id:'crypto-swing-liquidity',name:'Swing Liquidity',symbol,interval,rule:'Liquidity Sweep -> immediate next-candle confirmation -> next-candle OPEN entry'},candles,swings:analysis.swings,liquidity:{levels:analysis.liquidityLevels,sweeps:analysis.sweeps},signal:active?{value:active.direction,direction:active.direction,probability:active.probability,score:active.score,time:active.signalTime,price:active.entry,confirmationTime:active.confirmationTime}:analysis.signal,tradePlan:active,diagnostics:analysis.diagnostics,history:{summary:{totalTrades:history.length,wins,losses,open:0,winRate:wins+losses?Number((wins/(wins+losses)*100).toFixed(2)):0,totalR:Number(totalR.toFixed(2))},trades:history.slice(-200).reverse()}})}catch(e){return json({success:false,error:e?.message||'Crypto market data error'},500)}}
