import { CONFIG, analyze, buildHistory } from '../../src/scalping-strategy.js';
const INTERVAL='5min'; const STEP=300;
function epoch(v){const n=Number(v);if(Number.isFinite(n))return n>1e11?Math.floor(n/1000):Math.floor(n);const d=Date.parse(String(v||''));return Number.isFinite(d)?Math.floor(d/1000):NaN}
function keys(env){return[env.TWELVE_DATA_API_KEY,env.TWELVE_DATA_API_KEY_2,env.TWELVE_DATA_API_KEY_3,env.TWELVE_DATA_API_KEY_4].map(x=>String(x||'').trim()).filter(Boolean)}
async function twelve(key,n){const p=new URLSearchParams({symbol:'XAU/USD',interval:INTERVAL,outputsize:String(n),order:'ASC',timezone:'UTC',apikey:key}),r=await fetch('https://api.twelvedata.com/time_series?'+p),d=await r.json();if(!r.ok||d?.status==='error'||d?.code||!Array.isArray(d?.values))throw Error(d?.message||'Twelve Data request failed');const c=d.values.map(x=>({time:epoch(x.timestamp||x.datetime),open:Number(x.open),high:Number(x.high),low:Number(x.low),close:Number(x.close),volume:Number(x.volume||0)})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite));c.sort((a,b)=>a.time-b.time);return c}
async function yahoo(n){const u=new URL('https://query1.finance.yahoo.com/v8/finance/chart/XAUUSD=X');u.searchParams.set('range','5d');u.searchParams.set('interval','5m');u.searchParams.set('includePrePost','false');const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'}}),d=await r.json(),q=d?.chart?.result?.[0];if(!r.ok||!q?.timestamp)throw Error('Yahoo XAU/USD feed unavailable');const z=q.indicators?.quote?.[0]||{};return q.timestamp.map((t,i)=>({time:Number(t),open:Number(z.open?.[i]),high:Number(z.high?.[i]),low:Number(z.low?.[i]),close:Number(z.close?.[i]),volume:Number(z.volume?.[i]||0)})).filter(x=>[x.time,x.open,x.high,x.low,x.close].every(Number.isFinite)).slice(-n)}
async function market(n,env){const ks=keys(env),errors=[];for(let i=0;i<ks.length;i++){try{return{candles:await twelve(ks[i],n),provider:`Twelve Data #${i+1}`,fallback:i>0}}catch(e){errors.push(e?.message||'key failed')}}try{return{candles:await yahoo(n),provider:'Yahoo Finance',fallback:true,fallbackReason:errors.join('; ')}}catch(e){throw Error(`All market feeds failed: ${errors.join('; ')}; Yahoo: ${e?.message||'unavailable'}`)}}
function openTrade(signal,plan){return{id:`scalp-${signal.time}-${signal.direction}-ACTIVE`,interval:'5min',direction:signal.direction,signalTime:signal.time,entry:plan.entry,stopLoss:plan.stopLoss,tp1:plan.tp1,tp2:plan.tp2,tp3:plan.tp3,risk:plan.risk,realizedR:0,result:'OPEN',status:'OPEN',exit:null,exitTime:null,reason:'Active confirmed scalping signal'}}
export async function onRequest({request,env}){if(request.method!=='GET')return json({success:false,error:'Method not allowed'},405);try{const u=new URL(request.url),n=Math.min(500,Math.max(100,Math.floor(Number(u.searchParams.get('outputsize')||300)))),m=await market(n,env),now=Math.floor(Date.now()/1000),closed=m.candles.filter(c=>c.time+STEP<=now);if(closed.length<50)throw Error('Not enough completed 5M candles');const a=analyze(closed,null),history=buildHistory(closed),active=a.signal?.direction!=='WAIT'&&a.tradePlan?openTrade(a.signal,a.tradePlan):null,wins=history.filter(x=>x.result==='WIN').length,losses=history.filter(x=>x.result==='LOSS').length,totalR=history.reduce((s,x)=>s+Number(x.realizedR||0),0);return json({success:true,strategy:{id:'scalping-liquidity',name:'Wajid Scalping Liquidity',symbol:'XAU/USD',interval:'5min',parameters:CONFIG},dataProvider:m,market:{symbol:'XAU/USD',interval:'5min',price:closed.at(-1).close,lastCandleTime:closed.at(-1).time,candleCount:closed.length},candles:closed,swings:a.swings,liquidity:{sweeps:a.sweeps},signal:a.signal,tradePlan:a.tradePlan,activeTrade:active,diagnostics:a.diagnostics,history:{summary:{totalTrades:history.length,wins,losses,open:active?1:0,winRate:wins+losses?Number((wins/(wins+losses)*100).toFixed(2)):0,totalR:Number(totalR.toFixed(2))},trades:history}})}catch(e){return json({success:false,error:e?.message||'Scalping market error'},500)}}
function json(x,status=200){return new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'}})}
