// Wajid Swing Liquidity — Big Move Engine v1
// 15M location -> 5M expansion -> 1M entry. Completed-candle / next-open only.

const CONFIG={swingLeft:4,swingRight:3,atrLength:14,sweepLookback:24,confirmationBars:3,outputSize:300,zoneAtrHeight:.35,zoneMinScore:55,displacementAtr:.85,displacementBody:.45,maxStopAtr:4,slAtrBuffer:.20,minRRTarget:3,tp1R:1,tp2R:2,tp3R:3,tp4R:4,newsWindowMinutes:45,ruleVersion:"big-move-sd-v1"};

const N=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function atrAt(c,i,len=CONFIG.atrLength){const t=[];for(let j=Math.max(0,i-len+1);j<=i;j++){const x=c[j],p=c[j-1];if(x)t.push(p?Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)):x.high-x.low)}return avg(t)}
function atr(c){return c.length?atrAt(c,c.length-1):0}
function avgVol(c,i,n=20){const a=[];for(let j=Math.max(0,i-n);j<i;j++){const v=N(c[j]?.volume);if(v>0)a.push(v)}return avg(a)}
function vol(c,i){const cur=N(c[i]?.volume),base=avgVol(c,i);return{available:cur>0&&base>0,strong:cur>=base*1.05,ratio:base>0?cur/base:0}}
function swings(c){const h=[],l=[],L=CONFIG.swingLeft,R=CONFIG.swingRight;for(let i=L;i<c.length-R;i++){let hi=1,lo=1;for(let j=1;j<=L;j++){if(c[i-j].high>=c[i].high)hi=0;if(c[i-j].low<=c[i].low)lo=0}for(let j=1;j<=R;j++){if(c[i+j].high>c[i].high)hi=0;if(c[i+j].low<c[i].low)lo=0}if(hi)h.push({index:i,time:c[i].time,price:c[i].high,type:"SWING_HIGH",confirmedIndex:i+R});if(lo)l.push({index:i,time:c[i].time,price:c[i].low,type:"SWING_LOW",confirmedIndex:i+R})}return{highs:h,lows:l}}
function levels(c,s){const a=[...(s.highs||[]),...(s.lows||[])].sort((x,y)=>x.index-y.index);for(const z of a){z.touches=0;for(let i=z.confirmedIndex;i<c.length;i++)if(c[i].high>=z.price&&c[i].low<=z.price)z.touches++}return a}
function structureDirection(s){const h=s?.highs||[],l=s?.lows||[];if(h.length<2||l.length<2)return null;const H1=h.at(-2),H2=h.at(-1),L1=l.at(-2),L2=l.at(-1);if(H2.price>H1.price&&L2.price>L1.price)return"BULLISH";if(H2.price<H1.price&&L2.price<L1.price)return"BEARISH";return null}
const dirStruct=d=>d==="BUY"?"BULLISH":"BEARISH";

function zoneScore(c,p){const a=Math.max(atrAt(c,p.index),1e-9),end=Math.min(c.length-1,p.index+12),kind=p.type==="SWING_HIGH"?"Supply":"Demand";let move=0,wick=0,t=0;for(let i=p.index+1;i<=end;i++){const x=c[i];if(kind==="Supply")move=Math.max(move,p.price-x.low);else move=Math.max(move,x.high-p.price);if(Math.abs(x.high-p.price)<=a*.35||Math.abs(x.low-p.price)<=a*.35)t++;const w=kind==="Supply"?Math.max(x.high-Math.max(x.open,x.close),0):Math.max(Math.min(x.open,x.close)-x.low,0);wick=Math.max(wick,w/Math.max(x.high-x.low,1e-9))}const impulse=clamp(move/(a*2),0,1),fresh=clamp(1-(Math.max(t-1,0)/4),0,1);return 100*(.55*impulse+.25*wick+.20*fresh)}
function zones(c,s){return[...(s.highs||[]),...(s.lows||[])].slice(-80).map(p=>{const a=Math.max(atrAt(c,p.index),1e-9),h=a*CONFIG.zoneAtrHeight,m=p.price;return{kind:p.type==="SWING_HIGH"?"Supply":"Demand",mid:m,top:m+h/2,bot:m-h/2,score:zoneScore(c,p),index:p.index,time:p.time,broken:false}}).sort((a,b)=>b.score-a.score)}
function inZone(zs,kind,price){return zs.filter(z=>z.kind===kind&&!z.broken&&z.score>=CONFIG.zoneMinScore&&price>=z.bot&&price<=z.top).sort((a,b)=>b.score-a.score)[0]||null}
function targetZone(zs,kind,price,dir){let best=null,d=1e99;for(const z of zs)if(z.kind===kind&&!z.broken&&z.score>=CONFIG.zoneMinScore&&((dir==="BUY"&&z.mid>price)||(dir==="SELL"&&z.mid<price))){const x=Math.abs(z.mid-price);if(x<d){d=x;best=z}}return best}

function latestSweep(c,s){const start=Math.max(0,c.length-CONFIG.sweepLookback);let best=null;for(const p of s.highs||[]){for(let i=Math.max(start,p.confirmedIndex);i<c.length;i++){const x=c[i];if(x.high>p.price&&x.close<p.price){const z={type:"BEARISH",side:"HIGH",index:i,time:x.time,price:x.close,penetration:x.high-p.price,level:{type:p.type,price:p.price,index:p.index,time:p.time}};if(!best||i>best.index)best=z}}}for(const p of s.lows||[]){for(let i=Math.max(start,p.confirmedIndex);i<c.length;i++){const x=c[i];if(x.low<p.price&&x.close>p.price){const z={type:"BULLISH",side:"LOW",index:i,time:x.time,price:x.close,penetration:p.price-x.low,level:{type:p.type,price:p.price,index:p.index,time:p.time}};if(!best||i>best.index)best=z}}}return best}

function fvg(c,i,d){if(i<2)return false;return d==="BUY"?c[i].low>c[i-2].high&&c[i-1].close>c[i-1].open:c[i].high<c[i-2].low&&c[i-1].close<c[i-1].open}
function displacement(c,s,d){if(!s)return{confirmed:false};for(let i=s.index+1;i<=Math.min(c.length-1,s.index+CONFIG.confirmationBars);i++){const x=c[i],p=c[i-1],a=atrAt(c,i),r=Math.max(x.high-x.low,1e-9),br=Math.abs(x.close-x.open)/r,bodyDir=d==="BUY"?x.close>x.open:x.close<x.open,breaks=d==="BUY"?x.close>p.high:x.close<p.low,q=vol(c,i),gap=fvg(c,i,d);if(a>0&&r/a>=CONFIG.displacementAtr&&br>=CONFIG.displacementBody&&bodyDir&&(breaks||gap))return{confirmed:true,index:i,time:x.time,price:x.close,bodyRatio:br,atrRatio:r/a,fvg:gap,structureBreak:breaks,volume:q}}return{confirmed:false}}

function newsScore(news,d){if(!news)return{adjustment:0,blocked:false,label:"NEUTRAL"};const b=String(news.bias||"NEUTRAL").toUpperCase(),high=!!news.highImpactRecent,opp=(d==="BUY"&&b==="BEARISH")||(d==="SELL"&&b==="BULLISH"),ali=(d==="BUY"&&b==="BULLISH")||(d==="SELL"&&b==="BEARISH");return{adjustment:ali?5:opp?-5:0,blocked:high&&opp&&N(news.biasStrength)>=80,label:ali?"ALIGNED":opp?"OPPOSITE":"NEUTRAL"}}

function score(c,s,co,src,tgt,structure,news,d,ctx){let x=0,parts={};parts.zone=Math.min(N(src?.score)*.22,22);x+=parts.zone;parts.sweep=12;x+=12;parts.displacement=clamp(N(co.atrRatio)/1.5*12,0,12);x+=parts.displacement;parts.structure=structure===dirStruct(d)?14:0;x+=parts.structure;parts.fvg=co.fvg?8:0;x+=parts.fvg;parts.volume=co.volume?.available&&co.volume.strong?8:0;x+=parts.volume;parts.target=tgt&&tgt.score>=CONFIG.zoneMinScore?8:0;x+=parts.target;parts.htf=ctx?.structureDirection?(ctx.structureDirection===dirStruct(d)?10:-12):0;x+=parts.htf;const ns=newsScore(news,d);parts.news=ns.adjustment;x+=ns.adjustment;return{score:Math.round(clamp(x,0,100)),probability:Math.round(clamp(45+x*.5,0,95)),news:ns,components:parts}}

function plan(c,s,co,d,a,tgt){const ec=c[co.index+1];if(!ec)return{rejected:true,reason:"WAIT_ENTRY_CANDLE"};const e=N(ec.open),level=N(s.level?.price);const sl=d==="BUY"?Math.min(level,co.price)-a*CONFIG.slAtrBuffer:Math.max(level,co.price)+a*CONFIG.slAtrBuffer,risk=Math.max(Math.abs(e-sl),a*.25);if(!e||!sl||risk>a*CONFIG.maxStopAtr)return{rejected:true,reason:"STOP_TOO_WIDE",risk};if(tgt&&Math.abs(tgt.mid-e)<risk*CONFIG.minRRTarget)return{rejected:true,reason:"TARGET_TOO_CLOSE",risk};return{rejected:false,plan:{entry:e,stopLoss:sl,tp1:d==="BUY"?e+risk:e-risk,tp2:d==="BUY"?e+2*risk:e-2*risk,tp3:d==="BUY"?e+3*risk:e-3*risk,tp4:d==="BUY"?e+4*risk:e-4*risk,risk,rr:{tp1:1,tp2:2,tp3:3,tp4:4},entryTime:ec.time,entryRule:"NEXT_CANDLE_OPEN"}}}

function analyze(c,news=null,entryCandle=null,context={}){const a=atr(c),sw=swings(c),li=levels(c,sw),zs=zones(c,sw),structure=structureDirection(sw),s=latestSweep(c,sw),d=s?.type==="BULLISH"?"BUY":s?.type==="BEARISH"?"SELL":null,src=d?inZone(zs,d==="BUY"?"Demand":"Supply",s.level.price):null,tgt=d?targetZone(zs,d==="BUY"?"Supply":"Demand",c.at(-1)?.close,d):null,co=d?displacement(c,s,d):{confirmed:false},sc=d&&co.confirmed?score(c,s,co,src,tgt,structure,news,d,context):{score:0,probability:0,news:null,components:{}};const sig={value:"WAIT",direction:"WAIT",probability:0,score:sc.score,time:null,price:null,sweep:s,confirmation:co,rejection:null,news:sc.news||null,entryTime:null,target:tgt,sourceZone:src,components:sc.components};let rejection=null;if(!s)rejection="NO_RECENT_SWEEP";else if(!src||src.score<CONFIG.zoneMinScore)rejection="SWEEP_NOT_AT_STRONG_ZONE";else if(!co.confirmed)rejection="NO_DISPLACEMENT";else if(context.structureDirection&&context.structureDirection!==dirStruct(d))rejection="HTF_STRUCTURE_MISMATCH";else if(sc.news?.blocked)rejection="HIGH_IMPACT_NEWS_OPPOSITE";else if(sc.score<70)rejection="BIG_MOVE_SCORE_LOW";else if(!entryCandle||Number(entryCandle.time)<=Number(co.time))rejection="WAIT_ENTRY_CANDLE";let tradePlan=null;if(!rejection){const p=plan(c,s,co,d,a,tgt);if(p.rejected)rejection=p.reason;else{Object.assign(sig,{value:d,direction:d,probability:sc.probability,time:p.plan.entryTime,entryTime:p.plan.entryTime,price:p.plan.entry});tradePlan=p.plan}}sig.rejection=rejection;const v=vol(c,c.length-1),lh=sw.highs.at(-1),ll=sw.lows.at(-1);return{swings:sw,liquidityLevels:li,sweeps:s?[s]:[],zones:zs,signal:sig,tradePlan,structureDirection:structure,diagnostics:{atr:a,latestPrice:c.at(-1)?.close||null,latestSwingHigh:lh?.price||null,latestSwingLow:ll?.price||null,latestSweep:s?.type||"NONE",confirmation:co.confirmed?d:"NONE",volumeAvailable:v.available,volumeConfirmed:v.strong,riskFilter:tradePlan?{passed:true,rejected:false,reason:null,maxRisk:a*CONFIG.maxStopAtr,maxStopAtr:CONFIG.maxStopAtr}:{passed:false,rejected:["STOP_TOO_WIDE","TARGET_TOO_CLOSE"].includes(rejection),reason:rejection,maxRisk:a*CONFIG.maxStopAtr,maxStopAtr:CONFIG.maxStopAtr},structureDirection:structure,entryRule:tradePlan?.entryRule||null,entryTime:tradePlan?.entryTime||null,news:news||null,sourceZone:src,targetZone:tgt,bigMoveScore:sc.score,rejection,components:sc.components}}}

function historicalConfirmation(c,s){const d=s.type==="SWING_LOW"?"BUY":"SELL",sw={type:d==="BUY"?"BULLISH":"BEARISH",index:s.index,time:s.time,price:s.price,level:{type:s.type,price:s.price,index:s.index,time:s.time}};for(let i=Math.max(s.confirmedIndex,0);i<c.length;i++){const x=c[i];if(d==="BUY"&&x.low<s.price&&x.close>s.price){sw.index=i;const co=displacement(c,sw,d);if(co.confirmed)return co}if(d==="SELL"&&x.high>s.price&&x.close<s.price){sw.index=i;const co=displacement(c,sw,d);if(co.confirmed)return co}}return null}
function historicalPlan(c,s,co){const d=s.type==="SWING_LOW"?"BUY":"SELL",a=atrAt(c,co.index),ec=c[co.index+1];if(!ec)return null;const e=ec.open,sl=d==="BUY"?s.price-a*CONFIG.slAtrBuffer:s.price+a*CONFIG.slAtrBuffer,risk=Math.max(Math.abs(e-sl),a*.25);if(risk>a*CONFIG.maxStopAtr)return null;return{direction:d,entry:e,stopLoss:sl,tp1:d==="BUY"?e+risk:e-risk,tp2:d==="BUY"?e+2*risk:e-2*risk,tp3:d==="BUY"?e+3*risk:e-3*risk,tp4:d==="BUY"?e+4*risk:e-4*risk,risk,entryTime:ec.time,confirmationTime:co.time,entryRule:"NEXT_CANDLE_OPEN"}}
function resolve(c,i,p){const hit={tp1:false,tp2:false,tp3:false,tp4:false};let r=0;for(let j=i;j<c.length;j++){const x=c[j],sl=p.direction==="BUY"?x.low<=p.stopLoss:x.high>=p.stopLoss,ts=[["tp1",p.direction==="BUY"?x.high>=p.tp1:x.low<=p.tp1,1],["tp2",p.direction==="BUY"?x.high>=p.tp2:x.low<=p.tp2,2],["tp3",p.direction==="BUY"?x.high>=p.tp3:x.low<=p.tp3,3],["tp4",p.direction==="BUY"?x.high>=p.tp4:x.low<=p.tp4,4]];for(const[k,yes,v]of ts)if(yes&&!hit[k]){hit[k]=true;r+=v}if(sl)return{status:"CLOSED",result:"LOSS",realizedR:r-1,hit,exit:p.stopLoss,exitTime:x.time,reason:"SL hit; TP milestones counted"};if(hit.tp4)return{status:"CLOSED",result:"WIN",realizedR:r,hit,exit:p.tp4,exitTime:x.time,reason:"TP4 hit"}}return{status:"OPEN",result:"OPEN",realizedR:r,hit,exit:null,exitTime:null,reason:"TP4 and SL not reached"}}
function buildHistory(c,sw,symbol){const out=[];for(const s of[...(sw.highs||[]),...(sw.lows||[])].sort((a,b)=>a.index-b.index)){const co=historicalConfirmation(c,s);if(!co)continue;const p=historicalPlan(c,s,co);if(!p)continue;const o=resolve(c,co.index+1,p);out.push({id:String(p.entryTime)+"-"+p.direction+"-"+s.index,direction:p.direction,signalTime:p.entryTime,confirmationTime:p.confirmationTime,swingTime:s.time,swingType:s.type,swingPrice:Number(s.price.toFixed(2)),entry:Number(p.entry.toFixed(2)),stopLoss:Number(p.stopLoss.toFixed(2)),tp1:Number(p.tp1.toFixed(2)),tp2:Number(p.tp2.toFixed(2)),tp3:Number(p.tp3.toFixed(2)),tp4:Number(p.tp4.toFixed(2)),risk:Number(p.risk.toFixed(2)),tp1Hit:o.hit.tp1,tp2Hit:o.hit.tp2,tp3Hit:o.hit.tp3,tp4Hit:o.hit.tp4,hitTPs:Object.keys(o.hit).filter(k=>o.hit[k]),realizedR:Number(o.realizedR.toFixed(2)),result:o.result,status:o.status,exit:o.exit==null?null:Number(o.exit.toFixed(2)),exitTime:o.exitTime,reason:o.reason,entryRule:"NEXT_CANDLE_OPEN"})}return out}

export {CONFIG,analyze,buildHistory,structureDirection};