// CANONICAL Wajid Swing Liquidity strategy engine.
// IMPORTANT: Do not change strategy mathematics without explicit approval.

const CONFIG={swingLeft:15,swingRight:10,atrLength:14,sweepLookback:8,confirmationBars:6,outputSize:300,slAtrBuffer:.35,maxStopAtr:3,tp1R:1,tp2R:2,tp3R:3};
function atr(c){const tr=[];for(let i=0;i<c.length;i++){const x=c[i],p=c[i-1];tr.push(p?Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)):x.high-x.low)}const a=tr.slice(Math.max(0,tr.length-14));return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function avgVol(c,i,n=20){let s=0,k=0;for(let j=Math.max(0,i-n);j<i;j++){const v=Number(c[j].volume||0);if(v>0){s+=v;k++}}return k?s/k:0}
function vol(c,i){const current=Number(c[i]?.volume||0),average=avgVol(c,i);return{available:current>0&&average>0,strong:current>=average,current,average}}
function findSwings(c){const highs=[],lows=[];for(let i=15;i<c.length-10;i++){let h=true,l=true;for(let j=1;j<=15;j++){if(c[i-j].high>=c[i].high)h=false;if(c[i-j].low<=c[i].low)l=false}for(let j=1;j<=10;j++){if(c[i+j].high>c[i].high)h=false;if(c[i+j].low<c[i].low)l=false}if(h)highs.push({index:i,time:c[i].time,price:c[i].high,type:'SWING_HIGH',confirmedIndex:i+10,filled:false,fillIndex:null,fillTime:null,touches:0});if(l)lows.push({index:i,time:c[i].time,price:c[i].low,type:'SWING_LOW',confirmedIndex:i+10,filled:false,fillIndex:null,fillTime:null,touches:0})}return{highs,lows}}
function levels(c,s){const a=[...s.highs,...s.lows].sort((x,y)=>x.index-y.index);for(const l of a)for(let i=l.confirmedIndex;i<c.length;i++)if(c[i].high>=l.price&&c[i].low<=l.price){l.touches++;if(!l.filled){l.filled=true;l.fillIndex=i;l.fillTime=c[i].time}}return a}
function sweeps(c,s){const out=[],start=Math.max(0,c.length-8);for(const l of s.highs)for(let i=Math.max(l.confirmedIndex,start);i<c.length;i++)if(c[i].high>l.price&&c[i].close<l.price){out.push({type:'BEARISH',side:'HIGH',index:i,time:c[i].time,price:c[i].close,level:{type:l.type,price:l.price,index:l.index,time:l.time}});break}for(const l of s.lows)for(let i=Math.max(l.confirmedIndex,start);i<c.length;i++)if(c[i].low<l.price&&c[i].close>l.price){out.push({type:'BULLISH',side:'LOW',index:i,time:c[i].time,price:c[i].close,level:{type:l.type,price:l.price,index:l.index,time:l.time}});break}return out.sort((a,b)=>a.index-b.index)}
function confirm(c,s){if(!s)return{confirmed:false};for(let i=s.index+1,end=Math.min(c.length-1,s.index+6);i<=end;i++){const x=c[i],p=c[i-1];if(s.type==='BULLISH'&&x.close>x.open&&x.close>p.high)return{confirmed:true,direction:'BUY',index:i,time:x.time,price:x.close};if(s.type==='BEARISH'&&x.close<x.open&&x.close<p.low)return{confirmed:true,direction:'SELL',index:i,time:x.time,price:x.close}}return{confirmed:false}}
function score(c,s,co){if(!s||!co.confirmed)return{score:0,probability:0};let n=70;const v=vol(c,co.index);if(v.available&&v.strong)n+=15;if(s.level&&s.level.index>c.length-100)n+=10;const x=c[co.index],range=x.high-x.low;if(range>0&&Math.abs(x.close-x.open)/range>=.55)n+=5;n=Math.min(100,n);return{score:n,probability:Math.min(90,Math.max(0,Math.round(45+n*.45)))}}
function plan(c,sig,a){if(!sig||sig.direction==='WAIT')return{plan:null,rejected:false,reason:null,risk:null,maxRisk:null,structuralRisk:null};const e=sig.price,sp=Number(sig.sweep?.level?.price),struct=Number.isFinite(sp)?sp:(sig.direction==='BUY'?e-a:e+a),sr=Math.abs(e-struct),mr=a*3;if(!Number.isFinite(sr)||mr<=0||sr>mr)return{plan:null,rejected:true,reason:'STOP_TOO_WIDE',risk:sr,maxRisk:mr,structuralRisk:sr};const sl=sig.direction==='BUY'?Math.min(struct,e-a*.35):Math.max(struct,e+a*.35),risk=Math.max(Math.abs(e-sl),a*.25);if(risk>mr)return{plan:null,rejected:true,reason:'STOP_TOO_WIDE',risk,maxRisk:mr,structuralRisk:sr};return{plan:{entry:e,stopLoss:sl,tp1:sig.direction==='BUY'?e+risk:e-risk,tp2:sig.direction==='BUY'?e+risk*2:e-risk*2,tp3:sig.direction==='BUY'?e+risk*3:e-risk*3,risk,rr:{tp1:1,tp2:2,tp3:3}},rejected:false,reason:null,risk,maxRisk:mr,structuralRisk:sr}}
function analyze(c){const a=atr(c),sw=findSwings(c),li=levels(c,sw),ss=sweeps(c,sw),latest=ss.at(-1)||null,co=confirm(c,latest);let signal={value:'WAIT',direction:'WAIT',probability:0,score:0,time:null,price:null,sweep:null,confirmation:null,rejection:null},tradePlan=null,riskFilter={passed:false,rejected:false,reason:null,structuralRisk:null,maxRisk:null,maxStopAtr:3};if(latest&&co.confirmed&&c.length-1-co.index<=3){const st=score(c,latest,co),candidate={value:co.direction,direction:co.direction,probability:st.probability,score:st.score,time:co.time,price:co.price,sweep:latest,confirmation:co,rejection:null},pr=plan(c,candidate,a);riskFilter={passed:!pr.rejected,rejected:pr.rejected,reason:pr.reason,structuralRisk:pr.structuralRisk,maxRisk:pr.maxRisk,maxStopAtr:3};if(pr.rejected)signal={...candidate,value:'WAIT',direction:'WAIT',rejection:pr.reason};else{signal=candidate;tradePlan=pr.plan}}const lh=sw.highs.at(-1),ll=sw.lows.at(-1),v=vol(c,c.length-1);return{swings:sw,liquidityLevels:li,sweeps:ss,signal,tradePlan,diagnostics:{atr:a,latestPrice:c.at(-1)?.close||null,latestSwingHigh:lh?.price||null,latestSwingLow:ll?.price||null,latestSweep:latest?.type||'NONE',confirmation:co.confirmed?co.direction:'NONE',volumeAvailable:v.available,volumeConfirmed:v.strong,riskFilter}}}
function atrAt(c,i){const t=[];for(let j=Math.max(0,i-13);j<=i;j++){const x=c[j],p=c[j-1];t.push(p?Math.max(x.high-x.low,Math.abs(x.high-p.close),Math.abs(x.low-p.close)):x.high-x.low)}return t.length?t.reduce((a,b)=>a+b,0)/t.length:0}
function tradePlan(c,s,i,symbol){const e=Number(c[i]?.open),sp=Number(s.price),a=atrAt(c,i);if(!Number.isFinite(e)||!Number.isFinite(sp)||!a)return null;const buy=s.type==='SWING_LOW',sell=s.type==='SWING_HIGH';if(!buy&&!sell)return null;const sl=buy?Math.min(sp,e-a*.35):Math.max(sp,e+a*.35);if(buy?!(!(sl<e)):!(!(sl>e)))return null;const dist=Math.abs(e-sl);if(symbol.toUpperCase()==='XAU/USD'&&dist>10)return null;const risk=Math.max(dist,a*.25);return{direction:buy?'BUY':'SELL',entry:e,stopLoss:sl,tp1:buy?e+risk:e-risk,tp2:buy?e+2*risk:e-2*risk,tp3:buy?e+3*risk:e-3*risk,risk}}
function resolve(c,i,p){for(let j=i;j<c.length;j++){const x=c[j],sl=p.direction==='BUY'?x.low<=p.stopLoss:x.high>=p.stopLoss,tp=p.direction==='BUY'?x.high>=p.tp2:x.low<=p.tp2;if(sl&&tp)return{status:'CLOSED',result:'LOSS',realizedR:-1,exit:p.stopLoss,exitTime:x.time,barIndex:j,reason:'SL and TP2 touched in same candle; conservative SL'};if(sl)return{status:'CLOSED',result:'LOSS',realizedR:-1,exit:p.stopLoss,exitTime:x.time,barIndex:j,reason:'SL hit before TP2'};if(tp)return{status:'CLOSED',result:'WIN',realizedR:2,exit:p.tp2,exitTime:x.time,barIndex:j,reason:'TP2 hit'}}return{status:'OPEN',result:'OPEN',realizedR:0,exit:null,exitTime:null,barIndex:null,reason:'TP2 and SL not reached in available history'}}
function buildHistory(c,sw,symbol){const lv=[...(sw.highs||[]),...(sw.lows||[])].filter(x=>x&&(x.type==='SWING_HIGH'||x.type==='SWING_LOW')).map(x=>({...x,index:Number(x.index),price:Number(x.price)})).filter(x=>Number.isInteger(x.index)&&Number.isFinite(x.price)).sort((a,b)=>a.index-b.index);const out=[],used=new Set();let next=0;for(const s of lv){const i=s.index+1;if(i<next||i>=c.length)continue;const key=`${s.type}:${s.index}:${s.price.toFixed(4)}`;if(used.has(key))continue;const p=tradePlan(c,s,i,symbol);if(!p)continue;const o=resolve(c,i,p);used.add(key);out.push({id:`${c[i].time}-${p.direction}`,direction:p.direction,signalTime:c[i].time,swingTime:c[s.index]?.time||null,swingType:s.type,swingPrice:Number(s.price.toFixed(2)),entry:Number(p.entry.toFixed(2)),stopLoss:Number(p.stopLoss.toFixed(2)),tp1:Number(p.tp1.toFixed(2)),tp2:Number(p.tp2.toFixed(2)),tp3:Number(p.tp3.toFixed(2)),risk:Number(p.risk.toFixed(2)),realizedR:Number(Number(o.realizedR||0).toFixed(2)),result:o.result,status:o.status,exit:o.exit==null?null:Number(o.exit.toFixed(2)),exitTime:o.exitTime,reason:o.reason});if(o.barIndex!=null)next=o.barIndex+1;else break}return out}
export{CONFIG,analyze,buildHistory};
